export const actionType = {
    LOAD_USER_START: "LOAD_USER_START",
    LOAD_USER_SUCCESS: "LOAD_USER_SUCCESS",
    LOAD_USER_FAILURE: "LOAD_USER_FAILURE",
    LOAD_EXCHANGE_HISTORY_START: "LOAD_EXCHANGE_HISTORY_START",
    LOAD_EXCHANGE_HISTORY_SUCCESS: "LOAD_EXCHANGE_HISTORY_SUCCESS",
    LOAD_EXCHANGE_HISTORY_FAILURE: "LOAD_EXCHANGE_HISTORY_FAILURE",
    LOAD_RATES_START: "LOAD_RATES_START",
    LOAD_RATES_SUCCESS: "LOAD_RATES_SUCCESS",
    LOAD_RATES_FAILURE: "LOAD_RATES_FAILURE"
};

export const constantType = {
    LOAD_DASHBOARD_CONSTANT_START: "LOAD_DASHBOARD_CONSTANT_START",
    LOAD_DASHBOARD_CONSTANT_SUCCESS: "LOAD_DASHBOARD_CONSTANT_SUCCESS",
    LOAD_DASHBOARD_CONSTANT_FAILURE: "LOAD_DASHBOARD_CONSTANT_FAILURE",
    LOAD_DASHBOARD_CONSTANT_END: "LOAD_DASHBOARD_CONSTANT_END",
    LOAD_FREE_CREDIT_CONSTANT_START: "LOAD_FREE_CREDIT_CONSTANT_START",
    LOAD_FREE_CREDIT_CONSTANT_SUCCESS: "LOAD_FREE_CREDIT_CONSTANT_SUCCESS",
    LOAD_FREE_CREDIT_CONSTANT_FAILURE: "LOAD_FREE_CREDIT_CONSTANT_FAILURE",
    LOAD_FREE_CREDIT_CONSTANT_END: "LOAD_FREE_CREDIT_CONSTANT_END"
};
